language: c
before_install:
  - wget https://gist.github.com/petere/5893799/raw/apt.postgresql.org.sh
  - wget https://gist.github.com/petere/6023944/raw/pg-travis-test.sh
  - sudo sh ./apt.postgresql.org.sh
env:
  - PGVERSION=13
  - PGVERSION=12
  - PGVERSION=11
  - PGVERSION=10
  - PGVERSION=9.6
  - PGVERSION=9.5
  - PGVERSION=9.4
script: bash ./pg-travis-test.sh
